mounts = [
    "~/.config/nvim",
    "~/projects/personal/neovim/plugins",
]

caches = [
    ".local/share/nvim",
    ".local/state/nvim",
    ".cache/nvim",
    ".vim/undodir",
    ".supermaven",
    "@sbx-mise-nvim:.local/share/mise",
    "@sbx-mise-state-nvim:.local/state/mise",
]

start = "nvim ."
