mounts = [
    "~/.config/nvim",
    "~/projects/personal/neovim/plugins",
    "~/.solidtime_api_config",
    "~/.config/solidtime",
    "~/.gitconfig",
    "~/.git_",
    "~/.gitattributes",
]

caches = [
    ".local/share/nvim",
    ".local/state/nvim",
    ".cache/nvim",
    ".vim/undodir",
    ".supermaven",
    "@sbx-nvim-rocks:.local/share/nvim/lazy/luarocks.nvim/.rocks",
]

start = "nvim ."

allow-bare-repo = true

clipboard = true

forward-sockets = [
    "discord-ipc-0",
]
